version: "3.5"

services:
  drf:
    build: .
    hostname: drf
    container_name: drf
    command: python manage.py runserver 0.0.0.0:8001 #--settings=ccp_panel.settings.local
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    networks:
      - php-network
    external_links:
      - maria-db
    dns:
      - 8.8.8.8
    env_file: 
      - .env

networks:
  php-network:
    name: php-network
    external: true
